[project]
name = "codereveiwagent"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.12.5",
    "gradio>=5.49.1",
    "loguru>=0.7.3",
    "openai-agents>=0.4.0",
    "requests>=2.32.5",
]
